services: 
  app:
    build: .
    ports: 
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - QUART_SCHEMA_CONVERT_CASING=${QUART_SCHEMA_CONVERT_CASING}
    volumes:
      - ./app/alembic/versions:/app/alembic/versions
    networks:
      - petmatch-network

  db:
    image: postgres:16
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - petmatch-network


  redis:
    image: redis:7-alpine          # small, fast image
    ports:
      - "6379:6379"                # expose Redis on localhost:6379
    restart: always


volumes:
  pg_data:
    name: pg_data

networks:
  petmatch-network:
    driver: bridge
