services: 
  app:
    build: .
    ports: 
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_URL: ${DB_URL}

  db:
    image: postgres:16
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
