services: 
  app:
    image: ghcr.io/pet-match-itmo/backend:latest
    ports: 
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - QUART_SCHEMA_CONVERT_CASING=${QUART_SCHEMA_CONVERT_CASING}
    volumes:
      - ./app/alembic/versions:/app/alembic/versions
    restart: unless-stopped

  db:
    image: postgres:16
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
    name: pg_data
