name: build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        uses: ./.github/workflows/test.yaml
    
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v4
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ghcr.io/petmatch/backend:${{ github.sha }}

