name: tests

on: [push]

jobs:
    linter:
        runs-on: ubuntu-latest
        env:
            UV_CACHE_DIR: /tmp/.uv-cache
        steps:
            - uses: actions/checkout@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: "0.8.22"
                enable_cache: true
            
            - name: Install the project
              run: uv sync --locked
            
            - name: Run linter
              run: uv run ruff check
    
    pytest:
        runs-on: ubuntu-latest
        env:
            UV_CACHE_DIR: /tmp/.uv-cache
        steps:
            - uses: actions/checkout@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: "0.8.22"
                enable_cache: true
            
            - name: Install the project
              run: uv sync --locked
            
            - name: Run tests
              run: uv run pytest -v
